<template>
  <v-app>
    <Navbar />

    <v-main>
      <transition name="router-anim">
        <router-view></router-view>
      </transition>
    </v-main>
    <Snackbar />
  </v-app>
</template>
<script>
import Navbar from "./components/shared/NavBar";
import Snackbar from "./components/shared/Snackbar";
export default {
  components: {
    Navbar,
    Snackbar,
  },
};
</script>

<style lang="scss">
@import url("https://fonts.googleapis.com/css2?family=Oranienbaum&display=swap");
.hero-title {
  font-family: "Oranienbaum", serif !important;
  font-size: 3.5rem;
}

.v-btn--router {
  border-radius: 0px !important;
}

// Smooth router animation
.router-anim-enter-active {
  animation: coming 0.5s;
  animation-delay: 0.3s;
  opacity: 0;
}

.router-anim-leave-active {
  animation: going 0.3s;
}

@keyframes going {
  from {
    transform: translateX(0);
  }
  to {
    transform: translateX(-50px);
    opacity: 0;
  }
}

@keyframes coming {
  from {
    transform: translateX(-50px);
    opacity: 0;
  }
  to {
    transform: translateX(0px);
    opacity: 1;
  }
}

// Autogenerated sample code for SCSS reference
// #app {
//   font-family: Avenir, Helvetica, Arial, sans-serif;
//   -webkit-font-smoothing: antialiased;
//   -moz-osx-font-smoothing: grayscale;
//   text-align: center;
//   color: #2c3e50;
// }

// #nav {
//   padding: 30px;

//   a {
//     font-weight: bold;
//     color: #2c3e50;

//     &.router-link-exact-active {
//       color: #42b983;
//     }
//   }
// }
</style>
